name: Deploy
on:
    push:
        branches: [main]
jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy to Cloudflare Worker
        steps:
            - uses: actions/checkout@v4
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm build
            - name: Deploy
              uses: cloudflare/wrangler-action@v3
              env:
                  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
                  SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
              with:
                  # This is necessary to have the wrangler.jsonc support
                  wranglerVersion: 4.40.3
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  packageManager: pnpm
                  secrets: |
                      SUPABASE_URL
                      SUPABASE_SECRET_KEY
